packages = [
    "pandas",
    "geopandas",
    "scikit-learn",
    "numpy"
]

[[fetch]]
files = [
    "./ne_110m_admin_0_countries.shp",
    "./ne_110m_admin_0_countries.shx",
    "./ne_110m_admin_0_countries.dbf",
    "./ne_110m_admin_0_countries.prj",
    "./ne_110m_admin_0_countries.cpg",
    "./cities1000.txt"
]